FROM ubuntu14.04:v1
MAINTAINER devops <it@zqf.com.cn>
LABEL Description="it is used as a basic image for my study.I will update apt-get and install ssh."

RUN apt-get update
RUN apt-get install -y gcc
RUN apt-get install -y libmysqlclient-dev
RUN apt-get install -y libxml2      
RUN apt-get install -y libxml2-dev
RUN apt-get install -y snmp
RUN apt-get install -y libcurl4-openssl-dev
RUN apt-get install -y libsnmp-dev
RUN apt-get install -y unixODBC unixODBC-dev
RUN apt-get install -y ncurses-dev
RUN apt-get install -y libopenipmi-dev

